<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_players extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'game_state_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'name' => array(
				'type' => 'VARCHAR',
				'constraint' => 100,
			),
			'position' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'turn' => array(
				'type' => 'TINYINT',
				'constraint' => 1,
			),
			'control' => array(
				'type' => 'TINYINT',
				'constraint' => 1,
			),
			'pawnImage' => array(
				'type' => 'VARCHAR',
				'constraint' => 100,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('players', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('players');
	}
}