<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_games extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'name' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'game_state_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'password' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('games', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('games');
	}
}