<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_nodes extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'graph_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'x' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'y' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'color_ids' => array(
				'type' => 'VARCHAR',
				'constraint' => 500,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('nodes', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('nodes');
	}
}