<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Colors extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'nodeLinks' => ORM::has_many('\\Model\\NodeLinks')
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'name' => ORM::field('char[60]'),
			'hex_value' => ORM::field('char[60]'),
		);

	}
}