<?php

namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Edges extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'colors'  => ORM::belongs_to('\\Model\\Colors'),
            'graphs' => ORM::belongs_to('\\Model\\Graphs')
        );

		self::$fields = array(
            'id' => ORM::field('int[11]'),
            'graphs_id' => ORM::field('int[11]'),
            'colors_id' => ORM::field('int[11]'),
            'node1' => ORM::field('int[11]'),
            'node2' => ORM::field('int[11]'),
            'type' => ORM::field('char[60]'),
		);

	}

}