<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class GameStates extends ORM {

    public $table = 'game_states';
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'players'  => ORM::has_many('\\Model\\Players'),
            'games' => ORM::belongs_to('\\Model\\Games'),
            'graphs'  => ORM::belongs_to('\\Model\\Graphs')
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
            'game_id' => ORM::field('int[11]'),
            'graph_id' => ORM::field('int[11]'),
			'victory' => ORM::field('numeric[1]'),
			'turn' => ORM::field('int[11]'),
			'number_of_turns' => ORM::field('int[11]'),
			'reveal_turns' => ORM::field('char[50]'),
			'doubles' => ORM::field('int[11]'),
			'hiddens' => ORM::field('int[11]'),
			'players' => ORM::field('int[11]'),
			'log' => ORM::field('string'),
			'last_known_joker_position' => ORM::field('int[11]'),
			'turn_side' => ORM::field('char[50]'),
		);

	}
}