<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Graphs extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'nodes'  => ORM::has_many('\\Model\\Nodes'),
            'gameStates' => ORM::has_many('\\Model\\GameStates'),
            'edges'  => ORM::has_many('\\Model\\Edges'),
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'no_of_nodes' => ORM::field('int[11]'),
            'name' => ORM::field('char[100]')
		);

	}
}