<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Players extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'gameStates' => ORM::belongs_to('\\Model\\GameStates')
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'game_state_id' => ORM::field('int[11]'),
			'name' => ORM::field('char[100]'),
			'position' => ORM::field('int[11]'),
			'turn' => ORM::field('numeric[1]'),
			'control' => ORM::field('numeric[1]'),
			'pawnImage' => ORM::field('char[100]'),
		);

	}
}