<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Players extends ORM {

    const DEFAULT_SETTINGS = array(
        'criminal' => array(
            'position' => 130,
            'turn' => false
        ),
        'detective1' => array(
            'position' => 126,
            'turn' => true
        ),
        'detective2' => array(
            'position' => 127,
            'turn' => true
        ),
        'detective3' => array(
            'position' => 128,
            'turn' => true
        ),
        'detective4' => array(
            'position' => 129,
            'turn' => true
        )
    );
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'gameStates' => ORM::belongs_to('\\Model\\GameStates'),
            'characters' => ORM::belongs_to('\\Model\\Characters')
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'game_states_id' => ORM::field('int[11]'),
			'characters_id' => ORM::field('int[11]'),
			'position' => ORM::field('int[11]'),
			'turn' => ORM::field('numeric[1]'),
			'control' => ORM::field('numeric[1]'),
		);

	}
}