<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Games extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'gameStates'  => ORM::has_one('\\Model\\GameStates')
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'name' => ORM::field('char[40]'),
			'game_state_id' => ORM::field('int[11]'),
			'password' => ORM::field('char[255]'),
		);

	}
}