<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class NodeLinks extends ORM {

    public $table = 'node_links';
	
	public $primary_key = 'id';

	function _init()
	{

        self::$relationships = array(
            'colors'  => ORM::belongs_to('\\Model\\Colors'),
            'nodes' => ORM::belongs_to('\\Model\\Nodes')
        );

		self::$fields = array(
            'id' => ORM::field('int[11]'),
			'node_id' => ORM::field('int[11]'),
			'linked_node_id' => ORM::field('int[11]'),
			'color_id' => ORM::field('int[11]'),
		);

	}
}